"""empty message

Revision ID: 0be9f112b824
Revises:
Create Date: 2022-03-08 20:08:37.894793

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "0be9f112b824"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_position_id"), "position", ["id"], unique=False)
    op.create_table(
        "skill",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skill_id"), "skill", ["id"], unique=False)
    op.create_table(
        "position_skill",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.Column("skill_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["position.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_position_skill_id"), "position_skill", ["id"], unique=False)
    op.create_index(op.f("ix_position_skill_position_id"), "position_skill", ["position_id"], unique=False)
    op.create_index(op.f("ix_position_skill_skill_id"), "position_skill", ["skill_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_position_skill_skill_id"), table_name="position_skill")
    op.drop_index(op.f("ix_position_skill_position_id"), table_name="position_skill")
    op.drop_index(op.f("ix_position_skill_id"), table_name="position_skill")
    op.drop_table("position_skill")
    op.drop_index(op.f("ix_skill_id"), table_name="skill")
    op.drop_table("skill")
    op.drop_index(op.f("ix_position_id"), table_name="position")
    op.drop_table("position")
    # ### end Alembic commands ###
