"""empty message

Revision ID: 6a21b3af9460
Revises: 0be9f112b824
Create Date: 2022-03-10 21:40:51.257656

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "6a21b3af9460"
down_revision = "0be9f112b824"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("position_skill_skill_id_fkey", "position_skill", type_="foreignkey")
    op.create_foreign_key(None, "position_skill", "skill", ["skill_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "position_skill", type_="foreignkey")
    op.create_foreign_key("position_skill_skill_id_fkey", "position_skill", "position", ["skill_id"], ["id"])
    # ### end Alembic commands ###
